context("CNode tests")
test_that("dataone library loads", {
	library(dataone)
})
test_that("CNode constructors work", {
	library(dataone)
	cn <- CNode()
	expect_that(cn@endpoint, matches("https://cn.dataone.org/cn"))
	cn <- CNode("PROD")
	expect_that(cn@endpoint, matches("https://cn.dataone.org/cn"))
	cn <- CNode("DEV")
	expect_that(cn@endpoint, matches("https://cn-dev.test.dataone.org/cn"))
})
test_that("CNode listNodes() works", {
	library(dataone)
	cn <- CNode()
    xml <- listNodes(cn)
	val <- xmlName(xmlRoot(xml))
	expect_that(val, matches("nodeList"))
})
