context("CNode tests")
test_that("dataone library loads", {
	library(dataone)
})
test_that("CNode constructors work", {
	library(dataone)
	cn <- CNode()
	expect_that(cn@endpoint, matches("https://cn.dataone.org/cn"))
	cn <- CNode("PROD")
	expect_that(cn@endpoint, matches("https://cn.dataone.org/cn"))
	cn <- CNode("DEV")
	expect_that(cn@endpoint, matches("https://cn-dev.test.dataone.org/cn"))
})
test_that("CNode listNodes() works", {
	library(dataone)
	cn <- CNode()
	nodelist <- listNodes(cn)
	expect_that(length(nodelist) > 0, is_true())
	expect_that(class(nodelist[[1]]), matches("Node"))
	expect_that(nodelist[[1]]@identifier, matches("urn:node:"))
	expect_that(nodelist[[1]]@type, matches("cn|mn"))
	expect_that(nodelist[[1]]@state, matches("up"))
})
