---
title: "dataone R package overview"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
<!-- output: pdf_document -->
vignette: >
  %\VignetteIndexEntry{dataone R Package Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

## DataONE Overview 

The *dataone* R package enables R scripts to search, download and upload science data and metadata
to the DataONE Federation. This package calls DataONE web services that allow client programs
to interact with DataONE Coordinating Nodes (CN) and Member Nodes (MN). 

Searching for data in DataONE described in vignette *searching-dataone*. 

Downloading data from DataONE described in vignette *download-data*

Uploading data to DataONE is described in vignette *upload-data*. This document also
discusses maintenance operations that can be performed on datasets after they have been uploaded
to a DataONE MN, such as updating the dataset or updating system information about the
dataset.

If more detailed information is required than is provided by the *dataone* R package help, then in-depth documentation for the DataONE web services can be found at:

- Detailed overview [DataONE CN API](https://purl.dataone.org/architecturev2/apis/CN_APIs.html)
- Detailed overview [DataONE MN API](https://purl.dataone.org/architecturev2/apis/MN_APIs.html)

## New Features in DataONE Version 2.0
### 1. Series Identifiers
All data, metadata, and resource map objects in DataONE have a unique identifier, a Persistent
Identifier (PID). A PID is associated with one object in DataONE and always refers to the same object, the same set of bytes that are stored on the DataONE network. 

When an object is replaced in DataONE using MNode.update() for example, the new object must have a new 
PID assigned to it. The new object *obsoletes* the replaced object, and to access the new object, the
new pid must be used. Objects updated in this way create a series of objects, with the last object
added being unobsoleted by any other object and serving as the *head* of the series.

With DataONE V2.0, an additional, optional identifier can be associated with an object, the Series Identifier (SID).
The SIDs always accesses the object at the *head* of the object series. Using SIDs, the most current version
of an object can be obtained, without the need to determine the PID of the new object.

The older versions of the object can still be obtained using the PID for each object.

### 2. New Authentication Mechanism
Uploading data to DataONE required that a DataONE user identity be provided  In DataONE Version 1.x, the 
identity of a user was provided by an X.509 client certificate. DataONE Version 2.0
adds an additional method to provide identity information - an *authentication token*, also refered to as
an identity code. Authentication tokens can be used with nodes that have been upgrade to the DataONE Version 2.0 API.

The process of providing user identity information either via an X.509 certificate via an authentication token
is refered to as *authentication*.

Authentication tokens can be obtained from a user's DataONE account settings web page. This page
can be found by:

- Navigate to https://search.dataone.org
- Click *Sign in*, or *Sign up* if necessary
- Once signed in, click on the user name and select 'My account' in the drop down menu
- The *authentication token* (aka identification code) is displayed in the text window
- Note the identity string and expiration date of the token.
- Click on the *Copy* button to copy the token.
- in the R console enter the following command, replacing the token string value where indicated:
```
  options(authentication_token = "<paste token string here>")
```
- Note that this command can be entered in a user's ~/.Rprofile file so that this command is entered
when R is started.
- Remember that the console command must be re-entered with a new token value when the token expires

If the authentication token is defined as shown above, it will automatically be used when using methods
from the *dataone* R client.

<span style="color:red">
*The authentication token must be safegaurded like a password. Anyone with access to it can access content in DataONE as the user identity contained in the token. Care should be taken to not add this code to any published scripts or documents. This code will expire after a certain time period after which it will be necessary to obtain a new one.*
</span>

Detailed, technical information about user identities and authentication in DataONE can be viewed at 

[DataONE Authentication](https://purl.dataone.org/architecturev2/design/Authentication.html)

### 3. Ability To Update SystemMetadata
Metadata is maintained by DataONE for each object that has been uploaded to it. This SystemMetadata for an object contains
information such as the access policy that determines the users that can read or update the data, the data's format type,
how many replicated copies of the data to create, etc.

DataONE Version 2 adds the ability to update the SystemMetadata of a data object without having to update (replace) the data
object. So for example, an object can be uploaded to DataONE without having 'public' read enabled (the data creator or
*rightsholder* and possibly a specified list of users could have access however). At a later date, the SystemMetadata
could be updated to allow public read.

See ```help("updateSystemMetadata")``` for more information.

## Configurating DataONE
### Disabling 'warning' Messages Related To Authentication.
If a *dataone* R client method is called that might require authentication (create, update, etc) then a warning
message will be printed stating that the service requires authentication. Methods that upload or modify data in
DataONE always require authentication. Methods that read data, such as MNode.query will use authentication if
it is present. However, if an authentication method isn't available, then only data that is publicly available
will be accessed.

The *dataone* R client then, prints R warning messages if authentication is required or just recommended. 

These authentication warning messages can be disabled by either disabling all warning messages for R, or just
disabling warnings for just the authentication warning messages.

In order to disable warnings for all of R:
```
options(warn = -1)
```

See ```help("warnings")``` for more information about disabling and enabling warnings.

In order to disable warnings for just *dataone* R package authentication warnings:

```
options(auth_warn=FALSE)
```

To re-enable the authentication warnings:

```
options(auth_warn=TRUE)
```

## Known Issues with Version 2.0
### Error Using X.509 Certificates 

Using an X.509 certificate for DataONE authenticatin on certain versions of Mac OS X can cause the following error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
Problem with the local SSL certificate 
```  

Changes in the Mac OS X system libraries in OS X Mavericks have taken away support of these X.509 certificates.
A workaround to make these certificates usable on Mac OS X with R is to install a version of the *curl* R package
that supports these certificates. 

On Mac OS X, the libcurl library can be installed with either [Mac Ports](https://www.macports.org) package manager
or the [HomeBrew](http://brew.sh) package manager. The HomeBrew package manager can be significantly faster to install
but either one will work provided the directions shown below are followed.

You can check if you have MacPorts installed by entering the following command in a terminal window:

  port version
  

#### Create new *curl* package using MacPorts
If MacPorts is being used on your system, the following commands can be entered to install a *curl* package
that can read the certificate and allow them to be used by the *dataone* package for authentication
to a DataONE node. In a terminal window enter the commands:

```
sudo port install curl
```

```
Sys.setenv(LIB_DIR="/opt/local/lib")
Sys.setenv(INCLUDE_DIR="/opt/local/include")
install.packages("curl", type="source")
library(curl)
library(dataone)

# Remove the environment variables as they are no longer needed.
Sys.setenv(LIB_DIR="")
Sys.setenv(INCLUDE_DIR="")
```

At this point you should be able to use X.509 Certificates.

#### Create new *curl* package using HomeBrew
The HomeBrew software can be installed with the following command entered at a terminal window:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Once HomeBrew has been installed, you can get the required curl libraries by entering the command:

```
brew install curl --with-openssl
brew link curl --force
```

In the R console enter the commands:

```
Sys.setenv(LIB_DIR="/usr/local/opt/curl/lib")
Sys.setenv(INCLUDE_DIR="/usr/local/opt/curl/include")
install.packages("curl", type="source")
library(curl)
library(dataone)

# Remove the environment variables as they are no longer needed.
Sys.setenv(LIB_DIR="")
Sys.setenv(INCLUDE_DIR="")
```
At this point you should be able to use X.509 Certificates.
